project:
  type: website

website:
  title: "Arif Qodari | Tech Notes"
  site-url: https://arifqodari.github.io
  description: "Data Science and Artificial Intelligence"
  google-analytics: "G-SP1GGVPXSX"
  navbar:
    right:
      - about.qmd
      - talk.qmd
      - icon: github
        href: https://github.com/arifqodari/
      - icon: linkedin
        href: https://www.linkedin.com/in/arifqodari/
      - icon: medium
        href: https://medium.com/@arifqodari
format:
  html:
    theme: litera
    css: styles.css
